apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: smart-home
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  clusterIP: None
  selector:
    app: mongodb
