apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: smart-home
  labels:
    app: api
type: Opaque
stringData:
  MONGO_URI: "mongodb://student:student_secure_password@mongo.smart-home.svc.cluster.local:27017/smart-home?authSource=admin"

  JWT_ACCESS_SECRET: "your_super_secret_access_key_12345"
  JWT_REFRESH_SECRET: "your_super_secret_refresh_key_67890"

  REDIS_PASSWORD: "redis_secure_password"

  MINIO_ACCESS_KEY: "minio_admin"
  MINIO_SECRET_KEY: "minio_secure_password"

  RABBITMQ_USER: "student"
  RABBITMQ_PASS: "student_secure_rabbit_pass"

  YANDEX_CLIENT_ID: "779f5f109ee045d5b98bb78af6a090b3"
  YANDEX_CLIENT_SECRET: "1139a2317ec947a2b576c5a356580856"
  YANDEX_CALLBACK_URL: "http://localhost:4200/auth/oauth/yandex/callback"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_USER: "gummel543@gmail.com"
  SMTP_PASS: "kyeu jysu infs ujsl"
  SMTP_FROM: "gummel543@gmail.com"
